export const symbols = {
	"binance.com": {
		"ADAAUD": {
			local: "AUD",
			foreign: "ADA",
			split: "ADA/AUD",
			icon: "/forex-icons/ada.svg",
			blockRef: "ADAAUD",
			description: "",
		},
		"BNBAUD": {
			local: "AUD",
			foreign: "BNB",
			split: "BNB/AUD",
			icon: "/forex-icons/bnb.svg",
			blockRef: "BNBAUD",
			description: "",
		},
		"BTCAUD": {
			local: "AUD",
			foreign: "BTC",
			split: "BTC/AUD",
			icon: "/forex-icons/btc.svg",
			blockRef: "BTCAUD",
			description: "",
		},
		"DOGEAUD": {
			local: "AUD",
			foreign: "DOGE",
			split: "DOGE/AUD",
			icon: "/forex-icons/doge.svg",
			blockRef: "DOGEAUD",
			description: "",
		},
		"ETHAUD": {
			local: "AUD",
			foreign: "ETH",
			split: "ETH/AUD",
			icon: "/forex-icons/eth.svg",
			blockRef: "ETHAUD",
			description: "",
		},
		"LINKAUD": {
			local: "AUD",
			foreign: "LINK",
			split: "LINK/AUD",
			icon: "/forex-icons/link.svg",
			blockRef: "LINKAUD",
			description: "",
		},
		"SXPAUD": {
			local: "AUD",
			foreign: "SXP",
			split: "SXP/AUD",
			icon: "/forex-icons/sxp.svg",
			blockRef: "SXPAUD",
			description: "",
		},
		"TRXAUD": {
			local: "AUD",
			foreign: "TRX",
			split: "TRX/AUD",
			icon: "/forex-icons/trx.svg",
			blockRef: "TRXAUD",
			description: "",
		},
		"XRPAUD": {
			local: "AUD",
			foreign: "XRP",
			split: "XRP/AUD",
			icon: "/forex-icons/xrp.svg",
			blockRef: "XRPAUD",
			description: "",
		},
	}
};